name: Redeploy production and staging websites

on:
  push:
    branches:
      - master

jobs:
  prod:
    uses: ccl-france/mpcm-front/.github/workflows/prod.yml@master
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  staging:
    uses: ccl-france/mpcm-front/.github/workflows/staging.yml@master
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
