name: Build staging docker image and deploy

on:
  workflow_call:

jobs:
  build:
    name: Build Docker image and push
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ccl-france
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        env:
          IMAGE: ghcr.io/ccl-france/mpcm-front
        uses: docker/build-push-action@v2
        with:
          labels: |
            org.opencontainers.image.authors=${{ github.repository_owner }}
            org.opencontainers.image.created=${{ env.BUILD_DATE }}
            org.opencontainers.image.description=Created from commit ${{ env.GIT_SHA }} and ref ${{ env.GIT_REF }}
            org.opencontainers.image.ref.name=${{ env.GIT_REF }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ env.BUILD_VER }}
          push: true
          cache-from: type=registry,ref=${{ env.IMAGE }}:latest
          cache-to: type=inline
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd /srv/wbcp-front
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ccl-france --password-stdin
            docker-compose pull
            docker-compose up -d
            docker logout ghcr.io
